# This file was generated by GoReleaser. DO NOT EDIT.
cask "noema" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "d4201716eeb53687c702f9afe15ee8fd1013a17dee04673c5b8ae07b0385389b"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb211cf0bc7d0f9e8f87ddb01c7d292bc84fb227949bfe29c02ee9ccf6a69f60"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "add952751731f63605dd234e4f910cd1d76ec0a6364e48d16e61875e51aa21da"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ece7b71d184452960235c016146373c1b76ca27f082c7e7e9053d31a787f97e"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_arm64.tar.gz"
    end
  end

  name "noema"
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noema"]
    end
  end

  # No zap stanza required

end
