# This file was generated by GoReleaser. DO NOT EDIT.
cask "noema" do
  version "0.10.4"

  on_macos do
    on_intel do
      sha256 "2c38009ca9daddcedf4f1e627b9c676060a33cc3c9b5177e817466ca4dceb136"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8178fed1616f4e061ea0792cc24e11a2e348823ffef57811bb97f7700704178c"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "52ad56977b37a63f87de59d8f5c244b2439445d1da71591b593c832aff1e66a4"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0dfb34d0f088e0cd9b86150107310e74d4b18be8684983e9d242c6f207278bf"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_arm64.tar.gz"
    end
  end

  name "noema"
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noema"]
    end
  end

  # No zap stanza required

end
