# This file was generated by GoReleaser. DO NOT EDIT.
cask "noema" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "62db5c7b3ec472fd2c32e839e2bba6f634aa38e8c4dd9d7a41ecc84f98bca74f"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "760742b250872251076c34a4041e11e9732182884cf18836444a98653af52697"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "157eb54e48125b9775145072739d1e28b8e01f9521374c55dd3f732029d3b9ac"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2633e911178e5252336e9f8ba70a212fa94b54da66c245d5122018ab4fb61bbf"
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_arm64.tar.gz"
    end
  end

  name "noema"
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noema"]
    end
  end

  # No zap stanza required

end
