# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noema < Formula
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"
  version "0.9.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.9.3/noema_0.9.3_darwin_amd64.tar.gz"
      sha256 "a301fc10571b7cfe6c91b24ae8a832bc189425571de799a6a35363545d19dbdf"

      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.9.3/noema_0.9.3_darwin_arm64.tar.gz"
      sha256 "f7633333d4670424c6e2abae48fb16deef3240b3038fcb1e548feb5428fb9905"

      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.9.3/noema_0.9.3_linux_amd64.tar.gz"
      sha256 "200cf8a11b8ce3af9c375719df054b2210f2990238d510a193960d17afda4059"
      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.9.3/noema_0.9.3_linux_arm64.tar.gz"
      sha256 "a16b31f54b9f76f44602cc016ef449d2a8e1654f9f043cd550f9467e7d65d8ff"
      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  test do
    system "#{bin}/noema", "version"
  end
end
