# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoemaBeta < Formula
  desc "The intentional memory layer for your AI agents (beta channel)"
  homepage "https://github.com/Fail-Safe/Noema"
  version "0.10.0-beta.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.3/noema_0.10.0-beta.3_darwin_amd64.tar.gz"
      sha256 "25249423346fe460e67855a4679f79b0cb123a7f199b2f66b59cda357c220653"

      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.3/noema_0.10.0-beta.3_darwin_arm64.tar.gz"
      sha256 "a632ed791dcec85ed8895c8cb25cc64b226175971cba74b36800d4ad28a6e52a"

      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.3/noema_0.10.0-beta.3_linux_amd64.tar.gz"
      sha256 "d96beda4872dd7abcbb1b76c3bed2760ad0196b2db8f483440fe4c68da6cf081"
      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.3/noema_0.10.0-beta.3_linux_arm64.tar.gz"
      sha256 "dc002c35430652005bd91c2b3b6f6ea951367b83888c93a8ee72f6181b8d9485"
      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  conflicts_with "noema"

  test do
    system "#{bin}/noema", "version"
  end
end
