# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoemaBeta < Formula
  desc "The intentional memory layer for your AI agents (beta channel)"
  homepage "https://github.com/Fail-Safe/Noema"
  version "0.10.0-beta.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.4/noema_0.10.0-beta.4_darwin_amd64.tar.gz"
      sha256 "fbf19306fa71ce6f46d1e1ab217e76f3ed652c3da8e4997e66731be9b868b304"

      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.4/noema_0.10.0-beta.4_darwin_arm64.tar.gz"
      sha256 "4ae9fc49000d813c18df6eaed278bc38812a41474b186f65268fea52d6fee836"

      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.4/noema_0.10.0-beta.4_linux_amd64.tar.gz"
      sha256 "28640338e3b402343d78b09e534223c1a62bbf62e8391de1bfb1ff41f2cb2237"
      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.4/noema_0.10.0-beta.4_linux_arm64.tar.gz"
      sha256 "b3a1f0a5611afa79fe21b8b2a09a5f87f9982fcd6fdb9e6ff6d478ee56fbe42d"
      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  conflicts_with "noema"

  test do
    system "#{bin}/noema", "version"
  end
end
