# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noema < Formula
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.19.0/noema_0.19.0_darwin_amd64.tar.gz"
      sha256 "b516d48880351e50996d13e31bec3021b2d6cc8ab0e93aae44b48093880ccc2e"

      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.19.0/noema_0.19.0_darwin_arm64.tar.gz"
      sha256 "fa59ad17e16992e31dbf8a6c6d5ddb4270f58c6afdc433e427cd49fc875dfbb9"

      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.19.0/noema_0.19.0_linux_amd64.tar.gz"
      sha256 "1231f2318534a4de79dd9b25585f932c4b97f1cdb55390a2a34a37ddbbf59f43"
      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.19.0/noema_0.19.0_linux_arm64.tar.gz"
      sha256 "eaff3ee9c4ec2682d746f51e36582cdefc2b9cd100aaf0648ee36999bca61512"
      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  test do
    system "#{bin}/noema", "version"
  end
end
