# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noema < Formula
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"
  version "0.13.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.13.2/noema_0.13.2_darwin_amd64.tar.gz"
      sha256 "90aa886a1007a380dd0d4c7cc4d399035d3b26117375a957b66c320a462174ce"

      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.13.2/noema_0.13.2_darwin_arm64.tar.gz"
      sha256 "50e353854e294a2e49282338c706efdd1aa17a168e29038de308e95b5e9b9fc3"

      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.13.2/noema_0.13.2_linux_amd64.tar.gz"
      sha256 "d589ceb8229ccaefa537a317800388b05444166e99a87c3c3b9ba9556bc63fe9"
      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.13.2/noema_0.13.2_linux_arm64.tar.gz"
      sha256 "e3fba43017f4022f7339470db1b7af058065f45741d74224118cfb1ce0a23fe5"
      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  test do
    system "#{bin}/noema", "version"
  end
end
